#!/bin/sh

# Only run as superuser
if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

#if [ -z "${LOGFILE:-}" ]; then
#    echo "This script can't run standalone."
#    echo "Please use launch.sh to execute it."
#    exit 1
#fi
